### ISSUE TITLE
i need you 啊

### ISSUE THREAD

**Issue by zangjiahe** [destoryD/chaoxing-api#2]
能开放一下或者给个文件 我自己搭建嘛 挺需要的 如果可以 能给我发一下嘛 2210074929@qq.com

**Comment by destoryD** [comment]
网上提供接口的很多，自己去找吧

**Comment by zangjiahe** [comment]
网上的接口大都不稳定啊 您的接口一直很稳定




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"destoryD"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 晚上8:57
收件人:&nbsp;"destoryD/chaoxing-api"<chaoxing-api@noreply.github.com&gt;;
抄送:&nbsp;"a'ゞ小儿朗"<2210074929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [destoryD/chaoxing-api] i need you 啊 (#2)





 
网上提供接口的很多，自己去找吧

**Comment by destoryD** [comment]
我会考虑再次开放接口的，但是暂时不会

**Comment by zangjiahe** [comment]
呜呜~ i need you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"destoryD"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月13日(星期三) 晚上8:59
收件人:&nbsp;"destoryD/chaoxing-api"<chaoxing-api@noreply.github.com&gt;;
抄送:&nbsp;"a'ゞ小儿朗"<2210074929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [destoryD/chaoxing-api] i need you 啊 (#2)





 
我会考虑再次开放接口的，但是暂时不会

**Comment by zigou23** [comment]
+1emmm

**Comment by 1733735097** [comment]
希望早日开放 大佬这个挺好用的 收费也是可以的 如果可以的话  能给我发一下嘛1733735097@qq.com
