### ISSUE TITLE
可否咨询一下题库使用？

### ISSUE THREAD

**Issue by StonePanda** [destoryD/chaoxing-api#6]
你好，我们想建一个出题组卷的网站，可否咨询一下您收费版的具体接口？之前添加了您的QQ和QQ群一直没有收到通过通知~

**Comment by yjl307** [comment]
超星题库  百分百覆盖

**Comment by StonePanda** [comment]
您好，您的邮件已收到。

**Comment by StonePanda** [comment]
@yjl307 你加他的QQ群吧～我加上之后咨询了一下，感觉和我们的需求不是很契合，就没有使用，具体的信息你还是问下作者本人吧～

**Comment by yjl307** [comment]
百分百覆盖



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月13日 11:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [destoryD/chaoxing-api] 可否咨询一下题库使用？ (Issue #6) |

Closed #6 as completed.

**Comment by yjl307** [comment]
百分百覆盖正确 滴滴
